# Copyright 2026 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
"""Generates Pagefind search index."""

import asyncio
from pathlib import Path

from pagefind.index import IndexConfig, PagefindIndex
from sphinx.application import Sphinx

# Selectors excluded from Pagefind indexing to prevent UI/anchor artifacts
# from polluting search results.
_PW_EXCLUDE_SELECTORS = [
    '.pw-skip-link',  # "Skip to main content" a11y feature
    '#pw-toc-fab',  # Page ToC FAB
    'pw-header',  # Universal header
    'pw-breadcrumbs',  # Universal breadcrumbs
]

_SPHINX_EXCLUDE_SELECTORS = [
    '.headerlink',  # Section permalink symbols (¶)
    '.pst-collapse-sidebar-label',  # "Collapse Sidebar" button
    '.pst-expand-sidebar-label',  # "Expand Sidebar" button
    '#pst-back-to-top',  # "Back to top" button
]

_DOXYGEN_EXCLUDE_SELECTORS = [
    '.anchor',  # Member and section anchor links
    '.footer',  # "Generated by Doxygen" footer
    '#navrow1',  # Site nav
    '#Loading',  # Search results UI
    '#Searching',  # Search results UI
    '#NoMatches',  # Search results UI
]

_RUSTDOC_EXCLUDE_SELECTORS = [
    '.doc-anchor',  # Markdown heading anchor links (§)
    '.hideme',  # "Expand description" button
    '.main-heading .sub-heading .src',  # Link to source code
    '.skip-main-content',  # "Skip to main content" a11y feature
    '#copy-path',  # Item path copy button
    'body.rustdoc.src',  # Source pages
]

_EXCLUDE_SELECTORS = (
    _PW_EXCLUDE_SELECTORS
    + _SPHINX_EXCLUDE_SELECTORS
    + _DOXYGEN_EXCLUDE_SELECTORS
    + _RUSTDOC_EXCLUDE_SELECTORS
)


async def run_pagefind(outdir: str, srcdir: str):
    config = IndexConfig(
        exclude_selectors=_EXCLUDE_SELECTORS,
        verbose=False,
        keep_index_url=True,
        output_path=f'{outdir}/search',
        force_language='en',
    )
    async with PagefindIndex(config=config) as index:
        await index.add_directory(outdir)


def generate_search_index(
    app: Sphinx, exception: Exception | None = None
) -> None:
    if app.builder.format != 'html':
        return
    asyncio.run(run_pagefind(str(app.outdir), str(app.srcdir)))
