// Copyright 2026 The Pigweed Authors
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

package pw_ghish

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/andygrunwald/go-gerrit"
)

func TestResolveCIProvider_AutoAndExplicit(t *testing.T) {
	cfg := &Config{}

	// 1. Default auto on Pigweed host -> BuildbucketProvider
	p1 := ResolveCIProvider(cfg, DefaultProjectConfig(), nil, "pigweed-review.googlesource.com", nil)
	if p1.Name() != "buildbucket" {
		t.Errorf("expected buildbucket provider for pigweed host, got %q", p1.Name())
	}

	// 2. Default auto on Android Gerrit host -> CompositeCIProvider
	p2 := ResolveCIProvider(cfg, DefaultProjectConfig(), nil, "android-review.googlesource.com", nil)
	if p2.Name() != "composite" {
		t.Errorf("expected composite provider for android-review host, got %q", p2.Name())
	}

	// 3. Default auto on non-Android host when change has Presubmit-Ready label -> CompositeCIProvider
	changeWithLabel := &gerrit.ChangeInfo{
		Labels: map[string]gerrit.LabelInfo{
			"Presubmit-Ready": {},
		},
	}
	p3 := ResolveCIProvider(cfg, DefaultProjectConfig(), nil, "acme-review.googlesource.com", changeWithLabel)
	if p3.Name() != "composite" {
		t.Errorf("expected composite provider when change has Presubmit-Ready label, got %q", p3.Name())
	}

	// 4. Default auto on non-Android host when change has TreeHugger message -> CompositeCIProvider
	changeWithTH := &gerrit.ChangeInfo{
		Messages: []gerrit.ChangeMessageInfo{
			{Tag: "autogenerated:TreeHugger:Verify-Start"},
		},
	}
	p4 := ResolveCIProvider(cfg, DefaultProjectConfig(), nil, "acme-review.googlesource.com", changeWithTH)
	if p4.Name() != "composite" {
		t.Errorf("expected composite provider when change has TreeHugger message, got %q", p4.Name())
	}

	// 5. Explicit busytown only
	pcfgBusytown := DefaultProjectConfig()
	pcfgBusytown.CI.Providers = []string{"busytown"}
	p5 := ResolveCIProvider(cfg, pcfgBusytown, nil, "pigweed-review.googlesource.com", nil)
	if p5.Name() != "busytown" {
		t.Errorf("expected busytown provider when explicitly configured, got %q", p5.Name())
	}

	// 6. Explicit buildbucket + busytown
	pcfgBoth := DefaultProjectConfig()
	pcfgBoth.CI.Providers = []string{"buildbucket", "busytown"}
	p6 := ResolveCIProvider(cfg, pcfgBoth, nil, "pigweed-review.googlesource.com", nil)
	if p6.Name() != "composite" {
		t.Errorf("expected composite provider when both configured, got %q", p6.Name())
	}
}

func TestBusytownProvider_SearchBuilds_TreetopPresubmitTasks(t *testing.T) {
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)

	repoRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(repoRoot, ".ghish.toml"), []byte("[ci]\nproviders = [\"busytown\"]\n"), 0644); err != nil {
		t.Fatalf("failed to write .ghish.toml: %v", err)
	}
	oldMockCWD := MockCWD
	MockCWD = repoRoot
	t.Cleanup(func() {
		MockCWD = oldMockCWD
	})

	server.OnJSON("GET", "/changes/45678", http.StatusOK, gerrit.ChangeInfo{
		Number:          45678,
		Project:         "platform/system/core",
		Subject:         "Fix sensor HAL buffer handling",
		Status:          "NEW",
		CurrentRevision: "rev2",
		Revisions: map[string]gerrit.RevisionInfo{
			"rev2": {Number: 2},
		},
	})

	server.OnJSON("GET", "/changes/45678/revisions/2/treetop~presubmittasks", http.StatusOK, map[string]any{
		"tasks": []map[string]any{
			{
				"name":          "firmware_host_tests",
				"target":        "firmware_host_tests",
				"status":        "FAIL",
				"build_id":      "P99164207",
				"invocation_id": "I11223344",
				"workplan_id":   "L87654321",
				"summary":       "1 of 42 tests failed",
			},
			{
				"name":     "device_build_arm64-userdebug",
				"target":   "device_build_arm64-userdebug",
				"status":   "PASS",
				"build_id": "12345678",
			},
			{
				"name":     "lint_presubmit",
				"target":   "lint_presubmit",
				"status":   "RUNNING",
				"build_id": "P99164208",
			},
		},
	})

	// Test `gh pr checks 45678 --json number,patchset,checks`
	outJSON, err := executeCommand(RootCmd, "pr", "checks", "45678", "--json", "number,patchset,checks")
	if ExitCodeFor(err) != ExitCodeFailure {
		t.Fatalf("expected ExitCodeFailure from pr checks with failing check, got err=%v", err)
	}
	outJSON = strings.Split(outJSON, "\nError:")[0]

	var checkResp checksJSONResponse
	if err := json.Unmarshal([]byte(outJSON), &checkResp); err != nil {
		t.Fatalf("failed to unmarshal JSON output: %v\nOutput:\n%s", err, outJSON)
	}
	if len(checkResp.Checks) != 3 {
		t.Errorf("expected 3 checks, got: %+v", checkResp)
	}

	foundPendingURL := false
	foundSubmittedURL := false
	for _, c := range checkResp.Checks {
		if c.ID == "P99164207" {
			wantURL := "https://ci.android.com/builds/pending/P99164207/firmware_host_tests/latest"
			if c.URL != wantURL {
				t.Errorf("check P99164207 URL = %q, want %q", c.URL, wantURL)
			}
			foundPendingURL = true
		}
		if c.ID == "12345678" {
			wantURL := "https://ci.android.com/builds/submitted/12345678/device_build_arm64-userdebug/latest"
			if c.URL != wantURL {
				t.Errorf("check 12345678 URL = %q, want %q", c.URL, wantURL)
			}
			foundSubmittedURL = true
		}
	}
	if !foundPendingURL || !foundSubmittedURL {
		t.Errorf("missing expected Busytown check URLs in %+v", checkResp.Checks)
	}
}

type checksJSONResponse struct {
	Number              int         `json:"number"`
	Patchset            int         `json:"patchset"`
	Checks              []CheckItem `json:"checks"`
	OmittedExperimental int         `json:"omittedExperimental"`
}

func TestBusytownProvider_SearchBuilds_TreeHuggerMessagesFallback(t *testing.T) {
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)

	repoRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(repoRoot, ".ghish.toml"), []byte("[ci]\nproviders = [\"busytown\"]\n"), 0644); err != nil {
		t.Fatalf("failed to write .ghish.toml: %v", err)
	}
	oldMockCWD := MockCWD
	MockCWD = repoRoot
	t.Cleanup(func() {
		MockCWD = oldMockCWD
	})

	server.OnJSON("GET", "/changes/55555", http.StatusOK, gerrit.ChangeInfo{
		Number:          55555,
		Project:         "platform/system/core",
		Subject:         "Fallback TreeHugger message parsing",
		Status:          "NEW",
		CurrentRevision: "rev3",
		Revisions: map[string]gerrit.RevisionInfo{
			"rev3": {Number: 3},
		},
		Labels: map[string]gerrit.LabelInfo{
			"Presubmit-Verified": {
				All: []gerrit.ApprovalInfo{{Value: -1}},
			},
		},
		Messages: []gerrit.ChangeMessageInfo{
			{
				RevisionNumber: 3,
				Tag:            "autogenerated:TreeHugger:Verify-Start",
				Message:        "Patch Set 3:\n\nTreeHugger Robot has started presubmit.\nWorkplan ID: L99887766\n",
			},
			{
				RevisionNumber: 3,
				Tag:            "autogenerated:TreeHugger:Verify-Fail",
				Message:        "Patch Set 3: Presubmit-Verified-1\n\nWorkplan ID: L99887766\nFailed targets:\nhttps://ci.android.com/builds/pending/P99164207/sensor_unit_tests/latest\n",
			},
		},
	})

	// Return 404 on treetop~presubmittasks to trigger TreeHugger message fallback
	server.On("GET", "/changes/55555/revisions/3/treetop~presubmittasks", func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "Not Found", http.StatusNotFound)
	})

	outJSON, err := executeCommand(RootCmd, "pr", "checks", "55555", "--json", "number,patchset,checks")
	if ExitCodeFor(err) != ExitCodeFailure {
		t.Fatalf("expected ExitCodeFailure from pr checks with failing check, got err=%v", err)
	}
	outJSON = strings.Split(outJSON, "\nError:")[0]

	var checkResp checksJSONResponse
	if err := json.Unmarshal([]byte(outJSON), &checkResp); err != nil {
		t.Fatalf("failed to unmarshal JSON output: %v\nOutput:\n%s", err, outJSON)
	}
	if len(checkResp.Checks) != 1 || checkResp.Checks[0].Status != "FAILURE" {
		t.Fatalf("expected 1 failed check from TreeHugger fallback, got %+v", checkResp)
	}
	got := checkResp.Checks[0]
	if got.ID != "P99164207" {
		t.Errorf("got check ID %q, want P99164207", got.ID)
	}
	if got.Name != "sensor_unit_tests" {
		t.Errorf("got check Name %q, want sensor_unit_tests", got.Name)
	}
	wantURL := "https://ci.android.com/builds/pending/P99164207/sensor_unit_tests/latest"
	if got.URL != wantURL {
		t.Errorf("got check URL %q, want %q", got.URL, wantURL)
	}
}

func TestBusytownProvider_FailureLogs_TierA_LocalAccelerators(t *testing.T) {
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)

	repoRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(repoRoot, ".ghish.toml"), []byte("[ci]\nproviders = [\"busytown\"]\n"), 0644); err != nil {
		t.Fatalf("failed to write .ghish.toml: %v", err)
	}
	oldMockCWD := MockCWD
	MockCWD = repoRoot
	t.Cleanup(func() {
		MockCWD = oldMockCWD
	})

	// Enable Tier A local corp accelerators via stubs
	oldExists := BusytownFileExistsFn
	oldExec := BusytownExecCommandFn
	t.Cleanup(func() {
		BusytownFileExistsFn = oldExists
		BusytownExecCommandFn = oldExec
	})

	BusytownFileExistsFn = func(path string) bool {
		return path == FetchArtifactBinPath || path == AntsCLIBinPath
	}
	var executedCmds []string
	BusytownExecCommandFn = func(ctx context.Context, name string, args ...string) ([]byte, error) {
		cmdStr := name + " " + strings.Join(args, " ")
		executedCmds = append(executedCmds, cmdStr)
		if name == FetchArtifactBinPath {
			return []byte("[1/10] Compiling foo.cc\nFAILED: out/foo.o\nsrc/foo.cc:42:10: error: undeclared identifier 'bar'\nninja: build stopped: subcommand failed.\n"), nil
		}
		if name == AntsCLIBinPath {
			return []byte("FAIL: FooTest#testBufferOverflow (java.lang.AssertionError: expected 0 but was 1)\n"), nil
		}
		return nil, fmt.Errorf("unexpected command: %s", cmdStr)
	}

	server.OnJSON("GET", "/changes/45678", http.StatusOK, gerrit.ChangeInfo{
		Number:          45678,
		Project:         "platform/system/core",
		Subject:         "Fix sensor HAL",
		Status:          "NEW",
		CurrentRevision: "rev2",
		Revisions: map[string]gerrit.RevisionInfo{
			"rev2": {Number: 2},
		},
	})

	server.OnJSON("GET", "/changes/45678/revisions/2/treetop~presubmittasks", http.StatusOK, map[string]any{
		"tasks": []map[string]any{
			{
				"name":          "firmware_host_tests",
				"target":        "firmware_host_tests",
				"status":        "FAIL",
				"build_id":      "P99164207",
				"invocation_id": "I11223344",
			},
		},
	})

	out, err := executeCommand(RootCmd, "run", "view", "45678", "--log-failed")
	if err != nil {
		t.Fatalf("unexpected error from run view --log-failed: %v", err)
	}
	if !strings.Contains(out, "undeclared identifier 'bar'") {
		t.Errorf("expected build.log failure snippet in output, got:\n%s", out)
	}
	if !strings.Contains(out, "FooTest#testBufferOverflow") {
		t.Errorf("expected ants_cli failed test output in output, got:\n%s", out)
	}
	if len(executedCmds) != 2 {
		t.Errorf("expected both fetch_artifact and ants_cli to be invoked, got: %v", executedCmds)
	}
}

func TestBusytownProvider_FailureLogs_TierB_HTTPFallbackAndDirectID(t *testing.T) {
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)

	// Ensure Tier A local accelerators are disabled so Tier B HTTP fallback runs
	oldExists := BusytownFileExistsFn
	BusytownFileExistsFn = func(string) bool { return false }
	t.Cleanup(func() {
		BusytownFileExistsFn = oldExists
	})

	server.On("GET", "/android/internal/build/v3/builds/P99164207/firmware_host_tests/attempts/latest/artifacts/build.log/url", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprintf(w, `{"signedUrl": "%s/signed-artifacts/P99164207/build.log"}`, server.URL)
	})

	server.On("GET", "/signed-artifacts/P99164207/build.log", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain")
		io.WriteString(w, "Starting build...\nFAILED: out/sensor.o\nsensor.cc:99:2: error: static assertion failed\nninja: build stopped: subcommand failed.\n")
	})

	// Direct Busytown build ID + target inspection via `gh run view P99164207/firmware_host_tests --log-failed`
	out, err := executeCommand(RootCmd, "run", "view", "P99164207/firmware_host_tests", "--log-failed")
	if err != nil {
		t.Fatalf("unexpected error from run view P99164207/firmware_host_tests --log-failed: %v", err)
	}
	if !strings.Contains(out, "sensor.cc:99:2: error: static assertion failed") {
		t.Errorf("expected HTTP-fetched build.log snippet in output, got:\n%s", out)
	}
	if !strings.Contains(out, "https://ci.android.com/builds/pending/P99164207/firmware_host_tests/latest") {
		t.Errorf("expected ci.android.com URL in output, got:\n%s", out)
	}

	// Also verify `--target` flag syntax: `gh run view P99164207 --target firmware_host_tests --log-failed`
	out2, err := executeCommand(RootCmd, "run", "view", "P99164207", "--target", "firmware_host_tests", "--log-failed")
	if err != nil {
		t.Fatalf("unexpected error from run view P99164207 --target firmware_host_tests --log-failed: %v", err)
	}
	if !strings.Contains(out2, "sensor.cc:99:2: error: static assertion failed") {
		t.Errorf("expected HTTP-fetched build.log snippet with --target flag, got:\n%s", out2)
	}
}

func TestBusytownProvider_RerunBuilds_DryRunAndLiveFallback(t *testing.T) {
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)

	repoRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(repoRoot, ".ghish.toml"), []byte("[ci]\nproviders = [\"busytown\"]\n"), 0644); err != nil {
		t.Fatalf("failed to write .ghish.toml: %v", err)
	}
	oldMockCWD := MockCWD
	MockCWD = repoRoot
	t.Cleanup(func() {
		MockCWD = oldMockCWD
	})

	server.OnJSON("GET", "/changes/45678", http.StatusOK, gerrit.ChangeInfo{
		Number:          45678,
		Project:         "platform/system/core",
		Subject:         "Fix sensor HAL",
		Status:          "NEW",
		CurrentRevision: "rev2",
		Revisions: map[string]gerrit.RevisionInfo{
			"rev2": {Number: 2},
		},
	})

	server.OnJSON("GET", "/changes/45678/revisions/2/treetop~presubmittasks", http.StatusOK, map[string]any{
		"tasks": []map[string]any{
			{
				"name":     "firmware_host_tests",
				"target":   "firmware_host_tests",
				"status":   "FAIL",
				"build_id": "P99164207",
			},
		},
	})

	treetopRunActionCalled := 0
	treetopRunActionShould404 := false
	server.On("POST", "/changes/45678/revisions/2/treetop~runaction", func(w http.ResponseWriter, r *http.Request) {
		treetopRunActionCalled++
		if treetopRunActionShould404 {
			http.Error(w, "Not Found", http.StatusNotFound)
			return
		}
		server.RespondJSON(w, http.StatusOK, map[string]any{"status": "OK"})
	})

	reviewVotes := map[string]int{}
	server.On("POST", "/changes/45678/revisions/2/review", func(w http.ResponseWriter, r *http.Request) {
		var req gerrit.ReviewInput
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			t.Fatalf("failed to decode ReviewInput: %v", err)
		}
		for k, v := range req.Labels {
			reviewVotes[k] = v
		}
		server.RespondJSON(w, http.StatusOK, gerrit.ReviewResult{Labels: req.Labels})
	})

	// 1. Dry-run must NOT call treetop~runaction or review, and must print the dry-run line
	outDry, err := executeCommand(RootCmd, "run", "rerun", "45678", "--failed", "--dry-run")
	if err != nil {
		t.Fatalf("unexpected error from run rerun --dry-run: %v", err)
	}
	wantDry := "[dry-run] gerrit POST /changes/45678/revisions/2/treetop~runaction?service-id=presubmit&action-id=run (fallback: Presubmit-Ready+1)"
	if !strings.Contains(outDry, wantDry) {
		t.Errorf("expected dry-run output to contain %q, got:\n%s", wantDry, outDry)
	}
	if treetopRunActionCalled != 0 || len(reviewVotes) != 0 {
		t.Errorf("dry-run mutated server state: treetopRunActionCalled=%d, reviewVotes=%v", treetopRunActionCalled, reviewVotes)
	}

	// 2. Live rerun when treetop~runaction succeeds (200 OK)
	_, err = executeCommand(RootCmd, "run", "rerun", "45678", "--failed")
	if err != nil {
		t.Fatalf("unexpected error from live run rerun (treetop~runaction 200): %v", err)
	}
	if treetopRunActionCalled != 1 {
		t.Errorf("expected treetop~runaction to be called once, got %d", treetopRunActionCalled)
	}
	if len(reviewVotes) != 0 {
		t.Errorf("expected no fallback review vote when treetop~runaction succeeded, got %v", reviewVotes)
	}

	// 3. Live rerun when treetop~runaction returns 404 -> falls back to Presubmit-Ready+1
	treetopRunActionShould404 = true
	_, err = executeCommand(RootCmd, "run", "rerun", "45678", "--failed")
	if err != nil {
		t.Fatalf("unexpected error from live run rerun (404 fallback): %v", err)
	}
	if reviewVotes["Presubmit-Ready"] != 1 {
		t.Errorf("expected fallback vote Presubmit-Ready=+1, got %v", reviewVotes)
	}
}

func TestCompositeCIProvider_DualStackBuildbucketAndBusytown(t *testing.T) {
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)

	repoRoot := t.TempDir()
	tomlContent := `
[ci]
providers = ["buildbucket", "busytown"]
`
	if err := os.WriteFile(filepath.Join(repoRoot, ".ghish.toml"), []byte(tomlContent), 0644); err != nil {
		t.Fatalf("failed to write .ghish.toml: %v", err)
	}
	oldMockCWD := MockCWD
	MockCWD = repoRoot
	t.Cleanup(func() {
		MockCWD = oldMockCWD
	})

	server.OnJSON("GET", "/changes/77777", http.StatusOK, gerrit.ChangeInfo{
		Number:          77777,
		Project:         "platform/system/core",
		Subject:         "Dual-stack Buildbucket + Busytown CL",
		Status:          "NEW",
		CurrentRevision: "rev1",
		Revisions: map[string]gerrit.RevisionInfo{
			"rev1": {Number: 1},
		},
	})

	// Buildbucket SearchBuilds returns 1 LUCI build
	server.OnSearchBuilds(
		FakeBuild("876543210001", "bazel-presubmit", "FAILURE",
			WithBucket("try"),
			WithTimes("2026-03-31T10:00:00Z", "2026-03-31T10:05:00Z")),
	)

	// Busytown treetop~presubmittasks returns 1 Busytown build
	server.OnJSON("GET", "/changes/77777/revisions/1/treetop~presubmittasks", http.StatusOK, map[string]any{
		"tasks": []map[string]any{
			{
				"name":     "busytown_device_target",
				"target":   "busytown_device_target",
				"status":   "FAIL",
				"build_id": "P99164207",
			},
		},
	})

	// 1. Verify `gh pr checks 77777 --json number,patchset,checks` merges both providers
	outChecks, err := executeCommand(RootCmd, "pr", "checks", "77777", "--json", "number,patchset,checks")
	if ExitCodeFor(err) != ExitCodeFailure {
		t.Fatalf("expected ExitCodeFailure from pr checks with failing checks, got err=%v", err)
	}
	outChecks = strings.Split(outChecks, "\nError:")[0]
	var checkResp checksJSONResponse
	if err := json.Unmarshal([]byte(outChecks), &checkResp); err != nil {
		t.Fatalf("failed to unmarshal checks JSON: %v", err)
	}
	if len(checkResp.Checks) != 2 {
		t.Fatalf("expected 2 checks across both providers, got %+v", checkResp)
	}

	// 2. Verify `gh run list 77777` displays both providers with their respective URLs
	outList, err := executeCommand(RootCmd, "run", "list", "77777")
	if err != nil {
		t.Fatalf("unexpected error from run list: %v", err)
	}
	if !strings.Contains(outList, "https://ci.chromium.org/b/876543210001") {
		t.Errorf("expected Buildbucket URL in run list output, got:\n%s", outList)
	}
	if !strings.Contains(outList, "https://ci.android.com/builds/pending/P99164207/busytown_device_target/latest") {
		t.Errorf("expected Busytown URL in run list output, got:\n%s", outList)
	}

	// 3. Verify `gh run rerun 77777 --failed --dry-run` triggers dry-run for BOTH Buildbucket and Busytown
	outRerun, err := executeCommand(RootCmd, "run", "rerun", "77777", "--failed", "--dry-run")
	if err != nil {
		t.Fatalf("unexpected error from run rerun --dry-run: %v", err)
	}
	if !strings.Contains(outRerun, "bb add -cl") || !strings.Contains(outRerun, "bazel-presubmit") {
		t.Errorf("expected Buildbucket rerun command in dual-stack dry-run output, got:\n%s", outRerun)
	}
	if !strings.Contains(outRerun, "treetop~runaction") {
		t.Errorf("expected Busytown treetop~runaction in dual-stack dry-run output, got:\n%s", outRerun)
	}
}

func TestAndroidBuildOAuthScopes(t *testing.T) {
	hasAndroidBuildScope := false
	hasGerritScope := false
	for _, s := range DefaultAndroidBuildScopes {
		if s == ScopeAndroidBuildInternal {
			hasAndroidBuildScope = true
		}
		if s == ScopeGerritCodeReview {
			hasGerritScope = true
		}
	}
	if !hasAndroidBuildScope || !hasGerritScope {
		t.Errorf("DefaultAndroidBuildScopes = %v, want %q and %q", DefaultAndroidBuildScopes, ScopeAndroidBuildInternal, ScopeGerritCodeReview)
	}

	oldResolver := AndroidBuildTokenResolver
	AndroidBuildTokenResolver = func(ctx context.Context) (string, error) {
		return "mock-android-build-token", nil
	}
	t.Cleanup(func() {
		AndroidBuildTokenResolver = oldResolver
	})

	var gotAuthHeader string
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotAuthHeader = r.Header.Get("Authorization")
		w.WriteHeader(http.StatusOK)
	}))
	defer ts.Close()

	client := &http.Client{
		Transport: &AndroidBuildAuthTransport{Base: ts.Client().Transport},
	}
	resp, err := client.Get(ts.URL)
	if err != nil {
		t.Fatalf("client.Get failed: %v", err)
	}
	resp.Body.Close()

	if gotAuthHeader != "Bearer mock-android-build-token" {
		t.Errorf("Authorization header = %q, want %q", gotAuthHeader, "Bearer mock-android-build-token")
	}
}

func TestBusytownProvider_JSPBTreetopFallbackAndMergedPreMergePatchset(t *testing.T) {
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)

	repoRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(repoRoot, ".ghish.toml"), []byte("[ci]\nproviders = [\"busytown\"]\n"), 0644); err != nil {
		t.Fatalf("failed to write .ghish.toml: %v", err)
	}
	oldMockCWD := MockCWD
	MockCWD = repoRoot
	t.Cleanup(func() {
		MockCWD = oldMockCWD
	})

	t0 := time.Date(2026, 3, 20, 12, 0, 0, 0, time.UTC)
	t1 := time.Date(2026, 3, 20, 12, 4, 21, 0, time.UTC)

	// MERGED CL where Patchset 2 is the post-submit merge revision (no presubmit messages)
	// and Patchset 1 has the TreeHugger Verify-Start and Verify-Pass messages.
	server.OnJSON("GET", "/changes/88888", http.StatusOK, gerrit.ChangeInfo{
		Number:          88888,
		Project:         "platform/vendor/google/device",
		Subject:         "Merged Busytown CL with JSPB treetop response",
		Status:          "MERGED",
		CurrentRevision: "rev2",
		Revisions: map[string]gerrit.RevisionInfo{
			"rev1": {Number: 1},
			"rev2": {Number: 2},
		},
		Messages: []gerrit.ChangeMessageInfo{
			{
				Tag:     "autogenerated:TreeHugger:Verify-Start",
				Date:    gerrit.Timestamp{Time: t0},
				Message: "Patch Set 1:\n\nTreeHugger Robot has started presubmit.\nWorkplan ID: L32400030016797897\n",
			},
			{
				Tag:     "autogenerated:TreeHugger:Verify-Pass",
				Date:    gerrit.Timestamp{Time: t1},
				Message: "Patch Set 1: Presubmit-Verified+2\n\nTreeHugger Robot has finished the presubmit run.\nWorkplan ID: L32400030016797897\n",
			},
		},
	})

	// Return JSPB positional array ("[[...]]") on treetop~presubmittasks for both PS 2 and PS 1
	server.On("GET", "/changes/88888/revisions/2/treetop~presubmittasks", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, ")]}'\n[[[],\"280614394\"]]")
	})
	server.On("GET", "/changes/88888/revisions/1/treetop~presubmittasks", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, ")]}'\n[[[\"L32400030016797897\"],\"280614394\"]]")
	})

	// 1. Verify `gh pr checks 88888` reuses equivalent PS 1 builds and computes 4m21s duration
	outChecks, err := executeCommand(RootCmd, "pr", "checks", "88888")
	if err != nil {
		t.Fatalf("unexpected error from pr checks on merged Busytown CL: %v\nOutput:\n%s", err, outChecks)
	}
	if !strings.Contains(outChecks, "(from patchset 1)") {
		t.Errorf("expected equivalent patchset reuse annotation (from patchset 1) in output, got:\n%s", outChecks)
	}
	if !strings.Contains(outChecks, "4m21s") {
		t.Errorf("expected duration 4m21s computed between Verify-Start and Verify-Pass, got:\n%s", outChecks)
	}
	if !strings.Contains(outChecks, "https://ci.android.com/builds/workplans/L32400030016797897") {
		t.Errorf("expected workplan URL in output, got:\n%s", outChecks)
	}

	// 2. Verify `gh run rerun 88888 --dry-run` works without requiring --failed or -j on Busytown CLs
	outRerun, err := executeCommand(RootCmd, "run", "rerun", "88888", "--dry-run")
	if err != nil {
		t.Fatalf("unexpected error from run rerun --dry-run without --failed on Busytown CL: %v", err)
	}
	wantDry := "[dry-run] gerrit POST /changes/88888/revisions/2/treetop~runaction?service-id=presubmit&action-id=run (fallback: Presubmit-Ready+1)"
	if !strings.Contains(outRerun, wantDry) {
		t.Errorf("expected dry-run output %q, got:\n%s", wantDry, outRerun)
	}
}

type failingStubCIProvider struct {
	name string
	err  error
}

func (f *failingStubCIProvider) Name() string { return f.name }
func (f *failingStubCIProvider) SearchBuilds(context.Context, string, int, int, *GerritChangeInfo) ([]bbBuild, error) {
	return nil, f.err
}
func (f *failingStubCIProvider) GetBuildDetails(context.Context, string, *bbBuild) (*bbBuildDetails, error) {
	return nil, f.err
}
func (f *failingStubCIProvider) FetchFailureReportWithOptions(context.Context, bbBuild, FailureReportOptions) (*FailureReport, error) {
	return nil, f.err
}
func (f *failingStubCIProvider) RerunBuilds(context.Context, ChangeRef, []bbBuild, bool, io.Writer) error {
	return f.err
}

func TestCompositeCIProvider_OneProviderEmptyOrError(t *testing.T) {
	ctx := context.Background()

	// Case 1: Buildbucket returns 0 builds, Busytown returns 1 build -> returns 1 build
	server := NewMockGerritServer(t)
	SetMockGit(t, nil)
	server.OnSearchBuilds() // 0 Buildbucket builds
	change := &gerrit.ChangeInfo{
		Number: 99999,
		Messages: []gerrit.ChangeMessageInfo{
			{
				RevisionNumber: 1,
				Tag:            "autogenerated:TreeHugger:Verify-Pass",
				Message:        "Patch Set 1: Presubmit-Verified+2\nWorkplan ID: L11223344\n",
			},
		},
	}
	comp := &CompositeCIProvider{
		Providers: []CIProvider{
			&BuildbucketProvider{},
			&BusytownProvider{},
		},
	}
	builds, err := comp.SearchBuilds(ctx, "android-review.googlesource.com", 99999, 1, change)
	if err != nil {
		t.Fatalf("unexpected error when one provider returns 0 builds and the other succeeds: %v", err)
	}
	if len(builds) != 1 || builds[0].ID != "L11223344" {
		t.Errorf("expected 1 Busytown build L11223344, got %+v", builds)
	}

	// Case 2: One provider returns an error while another returns builds -> logs warning to ErrOut and returns builds
	var errBuf strings.Builder
	compWithErr := &CompositeCIProvider{
		Providers: []CIProvider{
			&failingStubCIProvider{name: "buildbucket", err: fmt.Errorf("rpc timeout")},
			&BusytownProvider{},
		},
		ErrOut: &errBuf,
	}
	builds2, err2 := compWithErr.SearchBuilds(ctx, "android-review.googlesource.com", 99999, 1, change)
	if err2 != nil {
		t.Fatalf("unexpected error when one provider fails and the other returns builds: %v", err2)
	}
	if len(builds2) != 1 || builds2[0].ID != "L11223344" {
		t.Errorf("expected 1 Busytown build L11223344, got %+v", builds2)
	}
	if !strings.Contains(errBuf.String(), "Warning: CI provider buildbucket failed: rpc timeout") {
		t.Errorf("expected warning logged to ErrOut, got %q", errBuf.String())
	}
}

func TestIsBusytownBuildID_And_ParseBusytownBuildTarget(t *testing.T) {
	tests := []struct {
		id       string
		target   string
		wantIsBT bool
		wantBID  string
		wantTgt  string
		wantOK   bool
	}{
		{id: "P99164207", wantIsBT: true, wantBID: "P99164207", wantTgt: "", wantOK: true},
		{id: "L87654321", wantIsBT: true, wantBID: "L87654321", wantTgt: "", wantOK: true},
		{id: "I1234567", wantIsBT: true, wantBID: "I1234567", wantTgt: "", wantOK: true},
		{id: "12345678", wantIsBT: true, wantBID: "12345678", wantTgt: "", wantOK: true},
		{id: "12345678", target: "device_arm64-userdebug", wantIsBT: true, wantBID: "12345678", wantTgt: "device_arm64-userdebug", wantOK: true},
		{id: "P99164207/sensor_unit_tests", wantIsBT: true, wantBID: "P99164207", wantTgt: "sensor_unit_tests", wantOK: true},
		{id: "12345678/device_arm64-userdebug", wantIsBT: true, wantBID: "12345678", wantTgt: "device_arm64-userdebug", wantOK: true},
		{id: "12345", wantIsBT: false, wantOK: false},
		{id: "8680709829694997521", wantIsBT: false, wantOK: false},
	}

	for _, tc := range tests {
		if got := IsBusytownBuildID(tc.id); got != tc.wantIsBT {
			t.Errorf("IsBusytownBuildID(%q) = %v, want %v", tc.id, got, tc.wantIsBT)
		}
		gotBID, gotTgt, gotOK := ParseBusytownBuildTarget(tc.id, tc.target)
		if gotOK != tc.wantOK || gotBID != tc.wantBID || gotTgt != tc.wantTgt {
			t.Errorf("ParseBusytownBuildTarget(%q, %q) = (%q, %q, %v), want (%q, %q, %v)",
				tc.id, tc.target, gotBID, gotTgt, gotOK, tc.wantBID, tc.wantTgt, tc.wantOK)
		}
	}
}
