// Copyright 2026 The Pigweed Authors
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.
#pragma once

// These includes also serve the `pw::EnumTraits` specializations emitted by the
// pw_enum code generator, which are appended to generated headers that include
// `pw_enum/generate.h`. Do not remove them without updating the generator.
#include <array>
#include <cstddef>
#include <string_view>
#include <type_traits>

/// @module{pw_enum}

namespace pw {

/// Compile-time metadata about an enum type.
///
/// The primary template is undefined. Specializations are generated
/// automatically for enums registered with `PW_ENUM`.
///
/// Specializations provide the following members. Enumerators that share a
/// value (aliases) are treated as a single *distinct value*.
///
/// - `enum_type` --- the enum type itself.
/// - `underlying_type` --- `std::underlying_type_t<enum_type>`.
/// - `kName` --- unqualified enum name, e.g. `"MyEnum"`.
/// - `kFullyQualifiedName` --- fully qualified enum name, e.g.
///   `"::my::ns::MyEnum"`.
/// - `kTokenDomain` --- the `pw_tokenizer` domain the enum is tokenized in.
/// - `kDistinctValueCount` --- number of distinct values; equals
///   `kValues.size()`.
/// - `kIsContiguous` --- whether the distinct values cover every integer from
///   `kMin` to `kMax` with no gaps.
/// - `kMin` / `kMax` --- smallest and largest enumerator values.
/// - `kValues` --- `std::array<enum_type, kDistinctValueCount>` of the distinct
///   values in ascending order.
/// - `IsValid(value)` --- returns whether an enumerator or integer value is a
///   valid enumerator; see `pw::IsValidEnum`.
///
/// @example{pw_enum/examples/traits.cc,pw_enum-examples-traits}
///
/// @warning Do not specialize `pw::EnumTraits` by hand. Specializations are
/// identified by an internal tag that only the code generator emits, so a
/// hand-written one is not recognized by `pw::has_enum_traits_v` and is
/// rejected by `pw::IsValidEnum`. To get traits for an enum, register it with
/// `PW_ENUM`.
template <typename T>
struct EnumTraits;

namespace internal {

template <typename T, typename = void>
struct HasEnumTraits : std::false_type {};

template <typename T>
struct HasEnumTraits<
    T,
    std::void_t<decltype(EnumTraits<T>::_pw_enum_internal_tag_do_not_use)>>
    : std::true_type {};

// Integer argument types accepted by `EnumTraits<Enum>::IsValid` and
// `pw::IsValidEnum`. `bool` arguments are rejected (`IsValid(true)` does not
// compile), though enums with a `bool` underlying type (`enum class E : bool`)
// can still be validated against integer arguments such as `0`, `1`, `2`, or
// `-1`.
template <typename Integer>
inline constexpr bool kIsInteger =
    std::is_integral_v<Integer> &&
    !std::is_same_v<std::remove_cv_t<Integer>, bool>;

// C++17 equivalent of C++20's std::cmp_less.
template <typename Lhs, typename Rhs>
constexpr bool CmpLess(Lhs lhs, Rhs rhs) {
  if constexpr (std::is_signed_v<Lhs> == std::is_signed_v<Rhs>) {
    return lhs < rhs;
  } else if constexpr (std::is_signed_v<Lhs>) {
    return lhs < 0 || static_cast<std::make_unsigned_t<Lhs>>(lhs) < rhs;
  } else {
    return rhs >= 0 && lhs < static_cast<std::make_unsigned_t<Rhs>>(rhs);
  }
}

// Checks whether an integer of arbitrary type is a valid enumerator of `Enum`.
template <typename Enum, typename Integer>
[[nodiscard]] constexpr bool IsValidInteger(Integer value) {
  static_assert(HasEnumTraits<Enum>::value,
                "pw::EnumTraits is not available for this type. Register the "
                "enum with PW_ENUM to generate it.");
  static_assert(kIsInteger<Integer>,
                "Enum values may only be checked against integers");
  using Underlying = std::underlying_type_t<Enum>;
  constexpr Underlying kMin = static_cast<Underlying>(EnumTraits<Enum>::kMin);
  constexpr Underlying kMax = static_cast<Underlying>(EnumTraits<Enum>::kMax);

  // Bounds check before casting so the conversion is always well defined.
  if (CmpLess(value, kMin) || CmpLess(kMax, value)) {
    return false;
  }
  if constexpr (EnumTraits<Enum>::kIsContiguous) {
    return true;
  } else {
    return EnumTraits<Enum>::IsValid(static_cast<Enum>(value));
  }
}

}  // namespace internal

/// True if `T` has a `pw::EnumTraits` specialization generated by `PW_ENUM`.
///
/// This is false for enums that were never registered with `PW_ENUM`, and for
/// hand-written `pw::EnumTraits` specializations, which are not supported.
template <typename T>
inline constexpr bool has_enum_traits_v = internal::HasEnumTraits<T>::value;

/// Returns whether `value` is a valid enumerator of its enum type.
template <typename Enum>
[[nodiscard]] constexpr bool IsValidEnum(Enum value) {
  static_assert(std::is_enum_v<Enum>, "Must be an enum");
  static_assert(has_enum_traits_v<Enum>,
                "pw::EnumTraits is not available for this enum. Register it "
                "with PW_ENUM to generate it.");
  return EnumTraits<Enum>::IsValid(value);
}

/// Returns whether the integer `value` is a valid enumerator of `Enum`. `Enum`
/// must be specified explicitly, e.g. `pw::IsValidEnum<MyEnum>(1)`.
template <typename Enum,
          typename Integer,
          typename = std::enable_if_t<internal::kIsInteger<Integer>>>
[[nodiscard]] constexpr bool IsValidEnum(Integer value) {
  static_assert(std::is_enum_v<Enum>, "Must be an enum");
  static_assert(has_enum_traits_v<Enum>,
                "pw::EnumTraits is not available for this enum. Register it "
                "with PW_ENUM to generate it.");
  return EnumTraits<Enum>::IsValid(value);
}

}  // namespace pw

/// @}
