# Copyright 2026 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

import("//build_overrides/pigweed.gni")

import("$dir_pw_async2/backend.gni")
import("$dir_pw_build/target_types.gni")
import("$dir_pw_thread/backend.gni")
import("$dir_pw_unit_test/test.gni")

config("public_include_path") {
  include_dirs = [ "public" ]
  visibility = [ ":*" ]
}

pw_source_set("pw_transport") {
  public_configs = [ ":public_include_path" ]
  public = [
    "public/pw_transport/socket.h",
    "public/pw_transport/transport.h",
  ]
  public_deps = [
    "$dir_pw_allocator",
    "$dir_pw_assert",
    "$dir_pw_async2",
    "$dir_pw_async2:value_future",
    "$dir_pw_buf",
    "$dir_pw_intrusive_ptr",
    "$dir_pw_memory",
    "$dir_pw_result",
    "$dir_pw_status",
    "$dir_pw_sync:lock_annotations",
  ]
  sources = [ "socket.cc" ]
}

# Intended for tests and examples, so restricted to upstream Pigweed.
pw_source_set("framed_tcp") {
  public_configs = [ ":public_include_path" ]
  public = [ "public/pw_transport/framed_tcp.h" ]
  public_deps = [
    ":pw_transport",
    "$dir_pw_allocator",
    "$dir_pw_async2:value_future",
    "$dir_pw_result",
    "$dir_pw_status",
    "$dir_pw_string:string",
    "$dir_pw_sync:lock_annotations",
    "$dir_pw_sync:mutex",
    "$dir_pw_sync:thread_notification",
    "$dir_pw_thread:thread",
  ]
  deps = [
    "$dir_pw_assert:check",
    "$dir_pw_buf",
    "$dir_pw_bytes",
    "$dir_pw_containers:dynamic_deque",
    "$dir_pw_log",
    "$dir_pw_string:to_string",
  ]
  sources = [ "framed_tcp.cc" ]
  visibility = [ "$dir_pigweed/*" ]
}

pw_test("transport_test") {
  enable_if = pw_async2_DISPATCHER_FOR_TEST_BACKEND != ""
  deps = [
    ":pw_transport",
    "$dir_pw_allocator:testing",
    "$dir_pw_async2:dispatcher",
    "$dir_pw_async2:testing",
    "$dir_pw_bytes",
    "$dir_pw_sync:interrupt_spin_lock",
  ]
  sources = [ "transport_test.cc" ]
}

pw_test("framed_tcp_test") {
  # The framed TCP transport uses POSIX sockets.
  enable_if = (current_os == "linux" || current_os == "mac") &&
              pw_async2_DISPATCHER_FOR_TEST_BACKEND != "" &&
              pw_thread_THREAD_BACKEND != ""
  deps = [
    ":framed_tcp",
    ":pw_transport",
    "$dir_pw_allocator:libc_allocator",
    "$dir_pw_allocator:synchronized_allocator",
    "$dir_pw_allocator:testing",
    "$dir_pw_async2",
    "$dir_pw_async2:testing",
    "$dir_pw_buf",
    "$dir_pw_bytes",
    "$dir_pw_result",
    "$dir_pw_status",
    "$dir_pw_stream:socket_stream",
    "$dir_pw_sync:mutex",
  ]
  sources = [ "framed_tcp_test.cc" ]
}

pw_test_group("tests") {
  tests = [
    ":framed_tcp_test",
    ":transport_test",
  ]
}
