# Copyright 2026 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

load("//pw_build:python.bzl", "pw_py_binary", "pw_py_library", "pw_py_test")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

# ==============================================================================
# Binaries
# ==============================================================================

pw_py_binary(
    name = "find_core_owners",
    srcs = ["pw_fortifier/find_core_owners.py"],
    deps = [":find_core_owners_lib"],
)

pw_py_binary(
    name = "demo_freshness_scanner",
    srcs = ["demo_freshness_scanner.py"],
    deps = [
        ":demo_freshness_scanner_lib",
    ],
)

pw_py_binary(
    name = "demo_issue_tracker",
    srcs = ["pw_fortifier/demo_issue_tracker.py"],
    deps = [
        ":demo_freshness_scanner_lib",
    ],
)

# ==============================================================================
# Libraries
# ==============================================================================

pw_py_library(
    name = "pw_fortifier",
    srcs = [
        "pw_fortifier/__init__.py",
    ],
    imports = ["."],
    deps = [
        ":demo_freshness_scanner_lib",
        ":find_core_owners_lib",
        ":freshness_scan_lib",
        ":pipeline_lib",
        ":security_scan_lib",
    ],
)

pw_py_library(
    name = "demo_freshness_scanner_lib",
    srcs = [
        "pw_fortifier/__init__.py",
        "pw_fortifier/demo_issue_tracker.py",
    ],
    imports = ["."],
    deps = [
        ":freshness_scan_lib",
        ":pipeline_lib",
    ],
)

pw_py_library(
    name = "find_core_owners_lib",
    srcs = [
        "pw_fortifier/__init__.py",
        "pw_fortifier/code_snippet.py",
        "pw_fortifier/find_core_owners.py",
        "pw_fortifier/git_utils.py",
    ],
    imports = ["."],
)

pw_py_library(
    name = "freshness_scan_lib",
    srcs = [
        "pw_fortifier/__init__.py",
        "pw_fortifier/bazel_cipd.py",
        "pw_fortifier/bazel_dep.py",
        "pw_fortifier/bazel_maven.py",
        "pw_fortifier/cargo.py",
        "pw_fortifier/cipd_setup.py",
        "pw_fortifier/cipd_utils.py",
        "pw_fortifier/copybara.py",
        "pw_fortifier/freshness_collector.py",
        "pw_fortifier/freshness_deduplicator.py",
        "pw_fortifier/freshness_result.py",
        "pw_fortifier/freshness_result_tracker.py",
        "pw_fortifier/freshness_scanner.py",
        "pw_fortifier/freshness_triager.py",
        "pw_fortifier/go_mod.py",
        "pw_fortifier/npm.py",
        "pw_fortifier/package_analyzer.py",
        "pw_fortifier/package_updater.py",
        "pw_fortifier/pip.py",
        "pw_fortifier/roll_generator.py",
        "pw_fortifier/semver.py",
    ],
    imports = ["."],
    deps = [
        ":find_core_owners_lib",
        ":pipeline_lib",
        "@pigweed_python_packages//packaging",
        "@pigweed_python_packages//requests",
    ],
)

pw_py_library(
    name = "security_scan_lib",
    srcs = [
        "pw_fortifier/__init__.py",
        "pw_fortifier/code_analyzer.py",
        "pw_fortifier/critic.py",
        "pw_fortifier/defect.py",
        "pw_fortifier/defect_scanner.py",
        "pw_fortifier/defect_tracker.py",
        "pw_fortifier/poc_and_fix_generator.py",
    ],
    imports = ["."],
    deps = [
        ":find_core_owners_lib",
        ":pipeline_lib",
    ],
)

pw_py_library(
    name = "pipeline_lib",
    srcs = [
        "pw_fortifier/__init__.py",
        "pw_fortifier/async_path.py",
        "pw_fortifier/bazelisk_utils.py",
        "pw_fortifier/build_utils.py",
        "pw_fortifier/code_editor.py",
        "pw_fortifier/collector.py",
        "pw_fortifier/deduplicator.py",
        "pw_fortifier/emitter.py",
        "pw_fortifier/issue.py",
        "pw_fortifier/issue_tracker.py",
        "pw_fortifier/path_enumerator.py",
        "pw_fortifier/pipeline_stage.py",
        "pw_fortifier/scanner.py",
        "pw_fortifier/triager.py",
    ],
    imports = ["."],
    deps = [
        ":find_core_owners_lib",
        "@pigweed_python_packages//pathspec",
        "@pigweed_python_packages//requests",
    ],
)

# ==============================================================================
# Tests
# ==============================================================================

pw_py_test(
    name = "code_editor_test",
    size = "small",
    srcs = [
        "code_editor_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "code_analyzer_test",
    size = "small",
    srcs = [
        "code_analyzer_test.py",
    ],
    deps = [
        ":security_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "bazel_cipd_test",
    size = "small",
    srcs = ["bazel_cipd_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "bazel_dep_test",
    size = "small",
    srcs = ["bazel_dep_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "bazel_maven_test",
    size = "small",
    srcs = ["bazel_maven_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
        "@pigweed_python_packages//requests",
    ],
)

pw_py_test(
    name = "bazelisk_utils_test",
    size = "small",
    srcs = ["bazelisk_utils_test.py"],
    deps = [":pipeline_lib"],
)

pw_py_test(
    name = "build_utils_test",
    size = "small",
    srcs = ["build_utils_test.py"],
    deps = [":pipeline_lib"],
)

pw_py_test(
    name = "cargo_test",
    size = "small",
    srcs = ["cargo_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "cipd_setup_test",
    size = "small",
    srcs = ["cipd_setup_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "cipd_utils_test",
    size = "small",
    srcs = ["cipd_utils_test.py"],
    deps = [":freshness_scan_lib"],
)

pw_py_test(
    name = "collector_test",
    size = "small",
    srcs = [
        "collector_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "copybara_test",
    size = "small",
    srcs = ["copybara_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "critic_test",
    size = "small",
    srcs = [
        "critic_test.py",
    ],
    deps = [
        ":security_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "deduplicator_test",
    size = "small",
    srcs = [
        "deduplicator_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "find_core_owners_test",
    size = "small",
    srcs = [
        "find_core_owners_test.py",
    ],
    deps = [
        ":find_core_owners_lib",
    ],
)

pw_py_test(
    name = "git_utils_test",
    size = "small",
    srcs = [
        "git_utils_test.py",
    ],
    deps = [
        ":find_core_owners_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "go_mod_test",
    size = "small",
    srcs = ["go_mod_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "npm_test",
    size = "small",
    srcs = ["npm_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "defect_scanner_test",
    size = "small",
    srcs = [
        "defect_scanner_test.py",
    ],
    deps = [
        ":security_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "freshness_scanner_test",
    size = "small",
    srcs = ["freshness_scanner_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "package_analyzer_test",
    size = "small",
    srcs = ["package_analyzer_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "semver_test",
    size = "small",
    srcs = ["semver_test.py"],
    deps = [
        ":freshness_scan_lib",
    ],
)

pw_py_test(
    name = "path_enumerator_test",
    size = "small",
    srcs = [
        "path_enumerator_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "pipeline_stage_test",
    size = "small",
    srcs = [
        "pipeline_stage_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "pip_test",
    size = "small",
    srcs = ["pip_test.py"],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//packaging",
        "@pigweed_python_packages//pyfakefs",
        "@pigweed_python_packages//requests",
    ],
)

pw_py_test(
    name = "issue_test",
    size = "small",
    srcs = [
        "issue_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "issue_tracker_test",
    size = "small",
    srcs = [
        "issue_tracker_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "demo_issue_tracker_test",
    size = "small",
    srcs = [
        "demo_issue_tracker_test.py",
    ],
    deps = [
        ":demo_freshness_scanner_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "defect_test",
    size = "small",
    srcs = [
        "defect_test.py",
    ],
    deps = [
        ":security_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "defect_tracker_test",
    size = "small",
    srcs = [
        "defect_tracker_test.py",
    ],
    deps = [
        ":security_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "freshness_deduplicator_test",
    size = "small",
    srcs = [
        "freshness_deduplicator_test.py",
    ],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "freshness_result_test",
    size = "small",
    srcs = [
        "freshness_result_test.py",
    ],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "freshness_result_tracker_test",
    size = "small",
    srcs = [
        "freshness_result_tracker_test.py",
    ],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "freshness_triager_test",
    size = "small",
    srcs = [
        "freshness_triager_test.py",
    ],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "triager_test",
    size = "small",
    srcs = [
        "triager_test.py",
    ],
    deps = [
        ":pipeline_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "roll_generator_test",
    size = "small",
    srcs = [
        "roll_generator_test.py",
    ],
    deps = [
        ":freshness_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)

pw_py_test(
    name = "poc_and_fix_generator_test",
    size = "small",
    srcs = [
        "poc_and_fix_generator_test.py",
    ],
    deps = [
        ":security_scan_lib",
        "@pigweed_python_packages//pyfakefs",
    ],
)
