# Copyright 2026 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
"""Tests for pip_scanner."""
# pylint: disable=protected-access

from datetime import date
import json
import os
import shutil
import subprocess
import tempfile
import unittest
from unittest.mock import patch, MagicMock

from pw_fortifier.pip_scanner import PipScanner
from pw_fortifier.package_scanner import PackageVersion


class TestPipScanner(unittest.TestCase):
    """Tests for PipScanner."""

    def setUp(self):
        """Set up test environment."""
        self.test_dir = tempfile.mkdtemp()

        # Create directory structure
        self.virtualenv_setup_dir = os.path.join(
            self.test_dir,
            "pw_env_setup",
            "py",
            "pw_env_setup",
            "virtualenv_setup",
        )
        os.makedirs(self.virtualenv_setup_dir)
        self.constraint_list = os.path.join(
            self.virtualenv_setup_dir, "constraint.list"
        )

        # Create fake constraint_hashes file
        hashes_content = (
            "# Autogenerated\n"
            "foo-pkg==1.0.0 \\\n"
            "    --hash=sha256:123\n"
            "bar-pkg==2.0.0 \\\n"
            "    --hash=sha256:456\n"
        )
        with open(self.constraint_list, "w") as f:
            f.write(hashes_content)

        # Create root pigweed.json
        self.pigweed_json_path = os.path.join(self.test_dir, 'pigweed.json')
        self.write_pigweed_json(
            ["pw_env_setup/py/pw_env_setup/virtualenv_setup/constraint.list"]
        )

        # Create fake setup.cfg files
        pw_foo_dir = os.path.join(self.test_dir, "pw_foo")
        os.makedirs(pw_foo_dir)
        pw_foo_cfg = os.path.join(pw_foo_dir, "setup.cfg")
        pw_foo_cfg_content = (
            "[metadata]\n"
            "name = pw_foo\n"
            "[options]\n"
            "install_requires =\n"
            "    foo-pkg >= 1.0.0\n"
            "    baz-pkg >= 3.0.0\n"
        )
        with open(pw_foo_cfg, "w") as f:
            f.write(pw_foo_cfg_content)

        pw_bar_dir = os.path.join(self.test_dir, "pw_bar")
        os.makedirs(pw_bar_dir)
        pw_bar_cfg = os.path.join(pw_bar_dir, "setup.cfg")
        pw_bar_cfg_content = (
            "[metadata]\n"
            "name = pw_bar\n"
            "[options]\n"
            "install_requires =\n"
            "    bar-pkg >= 2.0.0\n"
        )
        with open(pw_bar_cfg, "w") as f:
            f.write(pw_bar_cfg_content)

        # Pruned dir setup.cfg (should NOT be found by registry walk in main
        # app, but in test we manually call scan() so we control which files
        # are scanned. However, we should still create it to match setup if
        # needed.)
        out_dir = os.path.join(self.test_dir, "out")
        os.makedirs(out_dir)
        out_cfg = os.path.join(out_dir, "setup.cfg")
        with open(out_cfg, "w") as f:
            f.write("[metadata]\nname = out_pkg\n")

        # Write a fake OWNERS file
        owners_path = os.path.join(self.test_dir, 'OWNERS')
        with open(owners_path, 'w') as f:
            f.write(
                'owner-foo@google.com\n'
                'owner-bar@google.com\n'
                'owner-constraints@google.com\n'
                'owner-upstream@google.com\n'
            )

    def write_pigweed_json(self, requirements_files):
        """Helper to write pigweed.json."""
        content = {
            "pw": {
                "pw_env_setup": {
                    "virtualenv": {"requirements": requirements_files}
                }
            }
        }
        with open(self.pigweed_json_path, "w") as f:
            json.dump(content, f)

    def tearDown(self):
        """Tear down test environment."""
        shutil.rmtree(self.test_dir)

    def _mock_subprocess_run(self, cmd, **_kwargs):
        """Mock git commands."""
        if cmd[0] == "git":
            if cmd[1] == "log":
                return subprocess.CompletedProcess(
                    args=cmd,
                    returncode=0,
                    stdout="hash1 Fake commit\n",
                    stderr="",
                )
            if cmd[1] == "show":
                return subprocess.CompletedProcess(
                    args=cmd,
                    returncode=0,
                    stdout="pw_foo/setup.cfg\npw_bar/setup.cfg\n",
                    stderr="",
                )
            if cmd[1] == "blame":
                filepath = cmd[-1]
                if os.path.isabs(filepath):
                    rel_path = os.path.relpath(filepath, self.test_dir)
                else:
                    rel_path = filepath
                norm_rel_path = os.path.normpath(rel_path)

                if 'constraint.list' in norm_rel_path:
                    stdout = (
                        "hash1 (<owner-constraints@google.com> "
                        "2026-06-01 10:00:00 +0000 1) content\n"
                    )
                elif 'pigweed_upstream_requirements.txt' in norm_rel_path:
                    stdout = (
                        "hash1 (<owner-upstream@google.com> "
                        "2026-06-01 10:00:00 +0000 1) content\n"
                    )
                elif os.path.normpath('pw_foo/setup.cfg') in norm_rel_path:
                    stdout = (
                        "hash1 (<owner-foo@google.com> "
                        "2026-06-01 10:00:00 +0000 1) content\n"
                    )
                elif os.path.normpath('pw_bar/setup.cfg') in norm_rel_path:
                    stdout = (
                        "hash1 (<owner-bar@google.com> "
                        "2026-06-01 10:00:00 +0000 1) content\n"
                    )
                else:
                    stdout = (
                        "hash1 (<owner-default@google.com> "
                        "2026-06-01 10:00:00 +0000 1) content\n"
                    )
                return subprocess.CompletedProcess(
                    args=cmd, returncode=0, stdout=stdout, stderr=""
                )

        raise ValueError(f"Unexpected command: {cmd}")

    @patch("requests.get")
    @patch("subprocess.run")
    def test_scan(self, mock_run, mock_get):
        """Test scanning standard pip dependencies."""
        mock_run.side_effect = self._mock_subprocess_run

        # Mock requests.get
        def mock_requests_get(url, **_kwargs):
            mock_resp = MagicMock()
            mock_resp.status_code = 200

            if "foo-pkg" in url:
                data = {
                    "releases": {
                        "1.0.0": [
                            {
                                "upload_time_iso_8601": (
                                    "2026-01-02T12:00:00.000000Z"
                                )
                            }
                        ],
                        "1.1.0": [
                            {
                                "upload_time_iso_8601": (
                                    "2026-02-01T12:00:00.000000Z"
                                )
                            }
                        ],
                        "2.0.0": [
                            {
                                "upload_time_iso_8601": (
                                    "2026-06-05T12:00:00.000000Z"
                                )
                            }
                        ],
                    }
                }
            elif "bar-pkg" in url:
                data = {
                    "releases": {
                        "2.0.0": [
                            {
                                "upload_time_iso_8601": (
                                    "2026-02-02T12:00:00.000000Z"
                                )
                            }
                        ],
                        "2.1.0": [
                            {
                                "upload_time_iso_8601": (
                                    "2026-06-05T12:00:00.000000Z"
                                )
                            }
                        ],
                    }
                }
            elif "baz-pkg" in url:
                data = {
                    "releases": {
                        "3.0.0": [
                            {
                                "upload_time_iso_8601": (
                                    "2026-03-03T12:00:00.000000Z"
                                )
                            }
                        ],
                        "3.1.0": [
                            {
                                "upload_time_iso_8601": (
                                    "2026-06-05T12:00:00.000000Z"
                                )
                            }
                        ],
                    }
                }
            else:
                data = {}

            mock_resp.json.return_value = data
            return mock_resp

        mock_get.side_effect = mock_requests_get

        scanner = PipScanner(self.test_dir)
        scanner.date = date(2026, 6, 10)

        # Run lifecycle
        list(scanner.pre_scan())
        list(scanner.scan("pw_foo/setup.cfg"))
        list(scanner.scan("pw_bar/setup.cfg"))
        results = list(scanner.post_scan())

        self.assertEqual(len(results), 3)

        # 1. foo-pkg (resolved from constraint.list because version was equal)
        foo_res = next(r for r in results if r.package == "foo-pkg")
        self.assertEqual(
            foo_res.source,
            "pw_env_setup/py/pw_env_setup/virtualenv_setup/constraint.list",
        )
        self.assertEqual(foo_res.pkg_type, "pip")
        self.assertEqual(
            foo_res.current, PackageVersion("1.0.0", date(2026, 1, 2))
        )
        self.assertEqual(
            foo_res.earliest, PackageVersion("1.1.0", date(2026, 2, 1))
        )
        self.assertEqual(foo_res.tier, 2)
        self.assertEqual(foo_res.owner, "owner-constraints@google.com")

        # 2. bar-pkg (resolved from constraint.list)
        bar_res = next(r for r in results if r.package == "bar-pkg")
        self.assertEqual(
            bar_res.source,
            "pw_env_setup/py/pw_env_setup/virtualenv_setup/constraint.list",
        )
        self.assertEqual(bar_res.pkg_type, "pip")
        self.assertEqual(
            bar_res.current, PackageVersion("2.0.0", date(2026, 2, 2))
        )
        self.assertEqual(
            bar_res.earliest, PackageVersion("2.0.0", date(2026, 2, 2))
        )
        self.assertEqual(bar_res.tier, 2)
        self.assertEqual(bar_res.owner, "owner-constraints@google.com")

        # 3. baz-pkg (resolved from pw_foo/setup.cfg, not in constraint.list)
        baz_res = next(r for r in results if r.package == "baz-pkg")
        self.assertEqual(baz_res.source, "pw_foo/setup.cfg")
        self.assertEqual(baz_res.pkg_type, "pip")
        self.assertEqual(
            baz_res.current, PackageVersion("3.0.0", date(2026, 3, 3))
        )
        self.assertEqual(
            baz_res.earliest, PackageVersion("3.0.0", date(2026, 3, 3))
        )
        self.assertEqual(baz_res.tier, 2)
        self.assertEqual(baz_res.owner, "owner-foo@google.com")

    @patch("requests.get")
    @patch("subprocess.run")
    def test_scan_upstream(self, mock_run, mock_get):
        """Test scanning upstream pip requirements (tier 3)."""
        mock_run.side_effect = self._mock_subprocess_run

        # Create a fake pigweed_upstream_requirements.txt
        upstream_file_path = os.path.join(
            self.virtualenv_setup_dir, "pigweed_upstream_requirements.txt"
        )
        upstream_content = "breathe==4.35.0\n"
        with open(upstream_file_path, "w") as f:
            f.write(upstream_content)

        # Update pigweed.json to point to it
        self.write_pigweed_json(
            [
                "pw_env_setup/py/pw_env_setup/virtualenv_setup/"
                "pigweed_upstream_requirements.txt"
            ]
        )

        # Mock requests.get for breathe
        mock_resp = MagicMock()
        mock_resp.status_code = 200
        data = {
            "releases": {
                "4.35.0": [
                    {"upload_time_iso_8601": "2026-01-01T12:00:00.000000Z"}
                ],
                "4.36.0": [
                    {"upload_time_iso_8601": "2026-06-05T12:00:00.000000Z"}
                ],
            }
        }
        mock_resp.json.return_value = data
        mock_get.return_value = mock_resp

        scanner = PipScanner(self.test_dir)
        scanner.date = date(2026, 6, 10)

        # Run lifecycle
        list(scanner.pre_scan())
        # No setup.cfg scanned here
        results = list(scanner.post_scan())

        self.assertEqual(len(results), 1)
        res = results[0]
        self.assertEqual(res.package, "breathe")
        self.assertEqual(
            res.source,
            "pw_env_setup/py/pw_env_setup/virtualenv_setup/"
            "pigweed_upstream_requirements.txt",
        )
        self.assertEqual(res.pkg_type, "pip")
        self.assertEqual(
            res.current, PackageVersion("4.35.0", date(2026, 1, 1))
        )
        self.assertEqual(
            res.earliest, PackageVersion("4.35.0", date(2026, 1, 1))
        )
        self.assertEqual(res.tier, 3)  # TIER3_UPSTREAM
        self.assertEqual(res.owner, "owner-upstream@google.com")


if __name__ == "__main__":
    unittest.main()
