# Copyright 2026 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
"""Tests for pip."""
# pylint: disable=protected-access

from datetime import date
import json
import os
from pathlib import Path
import subprocess
import unittest
from unittest.mock import patch, MagicMock

from packaging.requirements import Requirement
from pyfakefs.fake_filesystem_unittest import TestCaseMixin
import requests
from pw_fortifier.async_path import AsyncPath
from pw_fortifier.pip import PipAnalyzer
from pw_fortifier.freshness_result import PackageVersion, FreshnessResult
from pw_fortifier.pipeline_stage import PipelineSink
from pw_fortifier.scanner import configure_stage_for_test


class TestPipAnalyzer(unittest.IsolatedAsyncioTestCase, TestCaseMixin):
    """Tests for PipAnalyzer."""

    def setUp(self):
        """Set up test environment."""
        self.setUpPyfakefs()
        self.test_dir = '/test'
        self.working_dir = '/working'
        self._date_patcher = None

        # Create directory structure & files
        self.virtualenv_setup_dir = (
            f'{self.test_dir}/pw_env_setup/py/pw_env_setup/virtualenv_setup'
        )
        self.constraint_list = f'{self.virtualenv_setup_dir}/constraint.list'

        hashes_content = (
            '# Autogenerated\n'
            'foo-pkg==1.0.0 \\\n'
            '    --hash=sha256:123\n'
            'bar-pkg==2.0.0 \\\n'
            '    --hash=sha256:456\n'
        )
        self.fs.create_file(self.constraint_list, contents=hashes_content)

        # Create root pigweed.json
        self.pigweed_json_path = f'{self.test_dir}/pigweed.json'
        self.write_pigweed_json(
            ['pw_env_setup/py/pw_env_setup/virtualenv_setup/constraint.list']
        )

        # Create fake setup.cfg files
        pw_foo_cfg_content = (
            '[metadata]\n'
            'name = pw_foo\n'
            '[options]\n'
            'install_requires =\n'
            '    foo-pkg >= 1.0.0\n'
            '    baz-pkg >= 3.0.0\n'
        )
        self.fs.create_file(
            f'{self.test_dir}/pw_foo/setup.cfg', contents=pw_foo_cfg_content
        )

        pw_bar_cfg_content = (
            '[metadata]\n'
            'name = pw_bar\n'
            '[options]\n'
            'install_requires =\n'
            '    bar-pkg >= 2.0.0\n'
        )
        self.fs.create_file(
            f'{self.test_dir}/pw_bar/setup.cfg', contents=pw_bar_cfg_content
        )

        self.fs.create_file(
            f'{self.test_dir}/out/setup.cfg',
            contents='[metadata]\nname = out_pkg\n',
        )

        # Write a fake OWNERS file
        owners_content = (
            'assignee-foo@google.com\n'
            'assignee-bar@google.com\n'
            'assignee-constraints@google.com\n'
            'assignee-upstream@google.com\n'
        )
        self.fs.create_file(f'{self.test_dir}/OWNERS', contents=owners_content)

    def write_pigweed_json(self, requirements_files):
        """Helper to write pigweed.json."""
        content = {
            'pw': {
                'pw_env_setup': {
                    'virtualenv': {'requirements': requirements_files}
                }
            }
        }
        Path(self.pigweed_json_path).write_text(json.dumps(content))

    def tearDown(self):
        """Tear down test environment."""
        if self._date_patcher is not None:
            self._date_patcher.stop()

    def set_date(self, d):
        """Sets the mocked package analyzer date."""
        if self._date_patcher is not None:
            self._date_patcher.stop()
        self._date_patcher = patch('pw_fortifier.package_analyzer.DATE', d)
        self._date_patcher.start()

    def _mock_subprocess_run(self, cmd, **_kwargs):
        """Mock git commands."""
        if cmd[0] == 'git':
            if len(cmd) > 2 and cmd[1] == '-C':
                cmd = [cmd[0]] + cmd[3:]
            if cmd[1] == 'log':
                return subprocess.CompletedProcess(
                    args=cmd,
                    returncode=0,
                    stdout='hash1 Fake commit\n',
                    stderr='',
                )
            if cmd[1] == 'show':
                return subprocess.CompletedProcess(
                    args=cmd,
                    returncode=0,
                    stdout='pw_foo/setup.cfg\npw_bar/setup.cfg\n',
                    stderr='',
                )
            if cmd[1] == 'blame':
                filepath = cmd[-1]
                if os.path.isabs(filepath):
                    rel_path = os.path.relpath(filepath, self.test_dir)
                else:
                    rel_path = filepath
                norm_rel_path = os.path.normpath(rel_path)

                if 'constraint.list' in norm_rel_path:
                    stdout = (
                        'hash1 (<assignee-constraints@google.com> '
                        '2026-06-01 10:00:00 +0000 1) content\n'
                    )
                elif 'pigweed_upstream_requirements.txt' in norm_rel_path:
                    stdout = (
                        'hash1 (<assignee-upstream@google.com> '
                        '2026-06-01 10:00:00 +0000 1) content\n'
                    )
                elif os.path.normpath('pw_foo/setup.cfg') in norm_rel_path:
                    stdout = (
                        'hash1 (<assignee-foo@google.com> '
                        '2026-06-01 10:00:00 +0000 1) content\n'
                    )
                elif os.path.normpath('pw_bar/setup.cfg') in norm_rel_path:
                    stdout = (
                        'hash1 (<assignee-bar@google.com> '
                        '2026-06-01 10:00:00 +0000 1) content\n'
                    )
                else:
                    stdout = (
                        'hash1 (<assignee-default@google.com> '
                        '2026-06-01 10:00:00 +0000 1) content\n'
                    )
                return subprocess.CompletedProcess(
                    args=cmd, returncode=0, stdout=stdout, stderr=''
                )

        raise ValueError(f'Unexpected command: {cmd}')

    @patch('requests.get')
    @patch('subprocess.run')
    async def test_run(self, mock_run, mock_get):
        """Test scanning standard pip dependencies."""
        mock_run.side_effect = self._mock_subprocess_run

        # Mock requests.get
        def mock_requests_get(url, **_kwargs):
            mock_resp = MagicMock()
            mock_resp.status_code = 200

            if 'foo-pkg' in url:
                data = {
                    'releases': {
                        '1.0.0': [
                            {
                                'upload_time_iso_8601': (
                                    '2026-01-02T12:00:00.000000Z'
                                )
                            }
                        ],
                        '1.1.0': [
                            {
                                'upload_time_iso_8601': (
                                    '2026-02-01T12:00:00.000000Z'
                                )
                            }
                        ],
                        '2.0.0': [
                            {
                                'upload_time_iso_8601': (
                                    '2026-06-05T12:00:00.000000Z'
                                )
                            }
                        ],
                    }
                }
            elif 'bar-pkg' in url:
                data = {
                    'releases': {
                        '2.0.0': [
                            {
                                'upload_time_iso_8601': (
                                    '2026-02-02T12:00:00.000000Z'
                                )
                            }
                        ],
                        '2.1.0': [
                            {
                                'upload_time_iso_8601': (
                                    '2026-06-05T12:00:00.000000Z'
                                )
                            }
                        ],
                    }
                }
            elif 'baz-pkg' in url:
                data = {
                    'releases': {
                        '3.0.0': [
                            {
                                'upload_time_iso_8601': (
                                    '2026-03-03T12:00:00.000000Z'
                                )
                            }
                        ],
                        '3.1.0': [
                            {
                                'upload_time_iso_8601': (
                                    '2026-06-05T12:00:00.000000Z'
                                )
                            }
                        ],
                    }
                }
            else:
                data = {}

            mock_resp.json.return_value = data
            return mock_resp

        mock_get.side_effect = mock_requests_get

        analyzer = PipAnalyzer()
        self.set_date(date(2026, 6, 10))

        consumer = PipelineSink()
        analyzer.connect(consumer)

        await configure_stage_for_test(
            analyzer,
            src_repo=self.test_dir,
            working_dir=self.working_dir,
            max_retries=0,
        )

        # Feed inputs
        await analyzer.input_queue.put(
            AsyncPath(self.test_dir) / 'pw_foo/setup.cfg'
        )
        await analyzer.input_queue.put(
            AsyncPath(self.test_dir) / 'pw_bar/setup.cfg'
        )
        await analyzer.input_queue.put(None)

        await analyzer.run()

        # Collect results
        results = []
        while True:
            result_path = await consumer.input_queue.get()
            if result_path is None:
                break
            result = await FreshnessResult.load(result_path)
            results.append(result)

        self.assertEqual(len(results), 3)

        # 1. foo-pkg (resolved from constraint.list because version was equal)
        foo_res = next(r for r in results if r.package == 'foo-pkg')
        self.assertEqual(
            foo_res.source,
            'pw_env_setup/py/pw_env_setup/virtualenv_setup/constraint.list',
        )
        self.assertEqual(foo_res.location.file, foo_res.source)
        self.assertEqual(foo_res.pkg_type, 'pip')
        self.assertEqual(
            foo_res.current, PackageVersion('1.0.0', date(2026, 1, 2))
        )
        self.assertEqual(
            foo_res.earliest, PackageVersion('1.1.0', date(2026, 2, 1))
        )
        self.assertEqual(foo_res.tier, 2)
        self.assertIsNone(foo_res.assignee)

        # 2. bar-pkg (resolved from constraint.list)
        bar_res = next(r for r in results if r.package == 'bar-pkg')
        self.assertEqual(
            bar_res.source,
            'pw_env_setup/py/pw_env_setup/virtualenv_setup/constraint.list',
        )
        self.assertEqual(bar_res.location.file, bar_res.source)
        self.assertEqual(bar_res.pkg_type, 'pip')
        self.assertEqual(
            bar_res.current, PackageVersion('2.0.0', date(2026, 2, 2))
        )
        self.assertEqual(
            bar_res.earliest, PackageVersion('2.0.0', date(2026, 2, 2))
        )
        self.assertEqual(bar_res.tier, 2)
        self.assertIsNone(bar_res.assignee)

        # 3. baz-pkg (resolved from pw_foo/setup.cfg, not in constraint.list)
        baz_res = next(r for r in results if r.package == 'baz-pkg')
        self.assertEqual(baz_res.source, os.path.normpath('pw_foo/setup.cfg'))
        self.assertEqual(baz_res.location.file, baz_res.source)
        self.assertEqual(baz_res.pkg_type, 'pip')
        self.assertEqual(
            baz_res.current, PackageVersion('3.0.0', date(2026, 3, 3))
        )
        self.assertEqual(
            baz_res.earliest, PackageVersion('3.0.0', date(2026, 3, 3))
        )
        self.assertEqual(baz_res.tier, 2)
        self.assertIsNone(baz_res.assignee)

    @patch('requests.get')
    @patch('subprocess.run')
    async def test_run_upstream(self, mock_run, mock_get):
        """Test scanning upstream pip requirements (tier 3)."""
        mock_run.side_effect = self._mock_subprocess_run

        # Create a fake pigweed_upstream_requirements.txt
        upstream_file_path = os.path.join(
            self.virtualenv_setup_dir, 'pigweed_upstream_requirements.txt'
        )
        self.fs.create_file(upstream_file_path, contents='breathe==4.35.0\n')

        # Update pigweed.json to point to it
        self.write_pigweed_json(
            [
                'pw_env_setup/py/pw_env_setup/virtualenv_setup/'
                'pigweed_upstream_requirements.txt'
            ]
        )

        # Mock requests.get for breathe
        mock_resp = MagicMock()
        mock_resp.status_code = 200
        data = {
            'releases': {
                '4.35.0': [
                    {'upload_time_iso_8601': '2026-01-01T12:00:00.000000Z'}
                ],
                '4.36.0': [
                    {'upload_time_iso_8601': '2026-06-05T12:00:00.000000Z'}
                ],
            }
        }
        mock_resp.json.return_value = data
        mock_get.return_value = mock_resp

        analyzer = PipAnalyzer()
        self.set_date(date(2026, 6, 10))

        consumer = PipelineSink()
        analyzer.connect(consumer)

        await configure_stage_for_test(
            analyzer,
            src_repo=self.test_dir,
            working_dir=self.working_dir,
            max_retries=0,
        )

        # No inputs, but we must still queue None to trigger shutdown.
        await analyzer.input_queue.put(None)

        await analyzer.run()

        # Collect results
        results = []
        while True:
            result_path = await consumer.input_queue.get()
            if result_path is None:
                break
            result = await FreshnessResult.load(result_path)
            results.append(result)

        self.assertEqual(len(results), 1)
        res = results[0]
        self.assertEqual(res.package, 'breathe')
        self.assertEqual(
            res.source,
            'pw_env_setup/py/pw_env_setup/virtualenv_setup/'
            'pigweed_upstream_requirements.txt',
        )
        self.assertEqual(res.location.file, res.source)
        self.assertEqual(res.pkg_type, 'pip')
        self.assertEqual(
            res.current, PackageVersion('4.35.0', date(2026, 1, 1))
        )
        self.assertEqual(
            res.earliest, PackageVersion('4.35.0', date(2026, 1, 1))
        )
        self.assertEqual(res.tier, 3)  # TIER3_UPSTREAM
        self.assertIsNone(res.assignee)

    def test_add_requirement_compatible_release(self) -> None:
        """Tests that ~= compatible release operator is supported."""
        analyzer = PipAnalyzer()
        req = Requirement('pyserial~=3.5.0')
        analyzer._add_requirement(req, 2, 'setup.cfg')
        self.assertIn('pyserial', analyzer._packages)
        version, tier, source = analyzer._packages['pyserial']
        self.assertEqual(version, '3.5.0')
        self.assertEqual(tier, 2)
        self.assertEqual(source, 'setup.cfg')

    def test_add_requirement_compound_specifiers(self) -> None:
        """Tests compound specifiers extract lower bound."""
        analyzer = PipAnalyzer()
        req = Requirement('pyserial>=3.5,<4.0')
        analyzer._add_requirement(req, 2, 'setup.cfg')
        self.assertIn('pyserial', analyzer._packages)
        version, tier, source = analyzer._packages['pyserial']
        self.assertEqual(version, '3.5')
        self.assertEqual(tier, 2)
        self.assertEqual(source, 'setup.cfg')

    def test_add_requirement_unsupported_operator(self) -> None:
        """Tests unsupported operators without lower bound raise ValueError."""
        analyzer = PipAnalyzer()
        req = Requirement('pyserial<4.0')
        with self.assertRaises(ValueError) as ctx:
            analyzer._add_requirement(req, 2, 'setup.cfg')
        self.assertIn("Unsupported operator '<'", str(ctx.exception))

    def test_add_requirement_bare_package(self) -> None:
        """Tests bare package requirements without specifiers are ignored."""
        analyzer = PipAnalyzer()
        req = Requirement('pyserial')
        analyzer._add_requirement(req, 2, 'setup.cfg')
        self.assertNotIn('pyserial', analyzer._packages)

    async def test_process_one_with_comments(self) -> None:
        """Tests _process_one parses requirements with comments."""
        cfg_path = os.path.join(self.test_dir, 'pw_cli', 'setup.cfg')
        content = (
            '[metadata]\n'
            'name = pw_cli\n'
            '[options]\n'
            'install_requires =\n'
            '    # Comment line\n'
            '    pyserial >= 3.5.0  # Comment on requirement\n'
            '    pyfakefs  # Inline comment\n'
            '    --extra-option\n'
        )
        self.fs.create_file(cfg_path, contents=content)

        analyzer = PipAnalyzer()
        await configure_stage_for_test(
            analyzer,
            src_repo=self.test_dir,
            working_dir=self.working_dir,
            max_retries=0,
        )

        await analyzer._process_one(AsyncPath(cfg_path))
        self.assertIn('pyserial', analyzer._packages)
        version, tier, _ = analyzer._packages['pyserial']
        self.assertEqual(version, '3.5.0')
        self.assertEqual(tier, 2)
        # pyfakefs is unpinned, so it's ignored without crashing
        self.assertNotIn('pyfakefs', analyzer._packages)

    @patch('requests.get')
    async def test_resolve_package_http_error(
        self, mock_get: MagicMock
    ) -> None:
        """Tests _resolve_package raises HTTPError when status is not 200."""
        mock_resp = MagicMock()
        mock_resp.status_code = 404
        mock_resp.raise_for_status.side_effect = requests.exceptions.HTTPError(
            '404 Client Error', response=mock_resp
        )
        mock_get.return_value = mock_resp

        analyzer = PipAnalyzer()
        with self.assertRaises(requests.exceptions.HTTPError):
            await analyzer._resolve_package('nonexistent', '1.0.0', 2)

    @patch('requests.get')
    async def test_resolve_package_missing_version_logs_error(
        self, mock_get: MagicMock
    ) -> None:
        """Tests _resolve_package logs error when version missing from PyPI."""
        mock_resp = MagicMock()
        mock_resp.status_code = 200
        mock_resp.json.return_value = {
            'releases': {
                '2.0.0': [{'upload_time_iso_8601': '2026-02-01T00:00:00Z'}]
            }
        }
        mock_get.return_value = mock_resp

        analyzer = PipAnalyzer()
        with self.assertLogs('pw_fortifier.pip', level='ERROR') as cm:
            earliest, current = await analyzer._resolve_package(
                'foo-pkg', '1.0.0', 2
            )
        self.assertIsNone(earliest)
        self.assertIsNone(current)
        self.assertTrue(
            any('not found in PyPI releases' in msg for msg in cm.output)
        )

    @patch('requests.get')
    async def test_resolve_package_version_normalization(
        self, mock_get: MagicMock
    ) -> None:
        """Tests _resolve_package normalizes versions according to PEP 440."""
        mock_resp = MagicMock()
        mock_resp.status_code = 200
        mock_resp.json.return_value = {
            'releases': {
                '3.5': [{'upload_time_iso_8601': '2026-01-01T00:00:00Z'}],
                '3.6': [{'upload_time_iso_8601': '2026-06-01T00:00:00Z'}],
            }
        }
        mock_get.return_value = mock_resp

        analyzer = PipAnalyzer()
        earliest, current = await analyzer._resolve_package(
            'pyserial', '3.5.0', 2
        )
        self.assertIsNotNone(current)
        self.assertIsNotNone(earliest)
        assert current is not None
        self.assertEqual(current.version, '3.5')
        self.assertEqual(current.timestamp, date(2026, 1, 1))

        mock_resp.json.return_value = {
            'releases': {
                '3.5.0.0': [{'upload_time_iso_8601': '2026-01-01T00:00:00Z'}],
                '3.5.0.1': [{'upload_time_iso_8601': '2026-06-01T00:00:00Z'}],
            }
        }
        earliest, current = await analyzer._resolve_package(
            'types-pyserial', '3.5', 2
        )
        self.assertIsNotNone(current)
        self.assertIsNotNone(earliest)
        assert current is not None
        self.assertEqual(current.version, '3.5.0.0')
        self.assertEqual(current.timestamp, date(2026, 1, 1))

    async def test_set_up_ingests_constraints(self) -> None:
        """Tests that _set_up reads both requirements and constraints."""
        req_path = 'pw_env_setup/py/pw_env_setup/virtualenv_setup/req.txt'
        const_path = 'pw_env_setup/py/pw_env_setup/virtualenv_setup/const.list'
        self.fs.create_file(
            f'{self.test_dir}/{req_path}',
            contents='req-pkg==1.0.0\n',
        )
        self.fs.create_file(
            f'{self.test_dir}/{const_path}',
            contents='const-pkg==2.0.0\n',
        )
        content = {
            'pw': {
                'pw_env_setup': {
                    'virtualenv': {
                        'requirements': [req_path],
                        'constraints': [const_path],
                    }
                }
            }
        }
        Path(self.pigweed_json_path).write_text(json.dumps(content))

        analyzer = PipAnalyzer()
        await configure_stage_for_test(
            analyzer,
            src_repo=self.test_dir,
            working_dir=self.working_dir,
            max_retries=0,
        )
        await analyzer._set_up()

        self.assertIn('req-pkg', analyzer._packages)
        self.assertEqual(analyzer._packages['req-pkg'][0], '1.0.0')
        self.assertIn('const-pkg', analyzer._packages)
        self.assertEqual(analyzer._packages['const-pkg'][0], '2.0.0')


if __name__ == '__main__':
    unittest.main()
