# Copyright 2020 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

import("//build_overrides/pigweed.gni")

import("$dir_pw_build/error.gni")
import("$dir_pw_build/target_types.gni")
import("$dir_pw_unit_test/test.gni")

config("public_include_path") {
  include_dirs = [ "public" ]
  visibility = [ ":*" ]
}

config("private_include_path") {
  include_dirs = [ "private" ]
  visibility = [ ":*" ]
}

config("overrides_include_path") {
  include_dirs = [
    "public_overrides",
    "private_overrides",
  ]
  visibility = [ ":*" ]
}

# See https://llvm.org/docs/LibFuzzer.html#fuzzer-friendly-build-mode
config("fuzzing_build_mode_unsafe_for_production") {
  defines = [ "FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION" ]
}

pw_test_group("tests") {
  group_deps = [
    ":fuzztest_tests",
    "examples/libfuzzer:tests",
  ]
}

pw_source_set("asan_default_options") {
  sources = [ "asan_default_options.c" ]
}

################################################################################
# FuzzTest is not supported for GN, so this module needs to provide stubs of the
# Pigweed-compatible subset of FuzzTest's interface, as well as extensions to
# support common Pigweed types.

pw_source_set("fuzztest.disabled") {
  public = [
    "private_overrides/pw_fuzzer/internal/fuzztest.h",
    "public/pw_fuzzer/asan_interface.h",
    "public/pw_fuzzer/fuzztest.h",
    "public_overrides/fuzztest/fuzztest.h",
  ]
  public_configs = [
    ":public_include_path",
    ":overrides_include_path",
  ]
  public_deps = [
    dir_pw_containers,
    dir_pw_result,
    dir_pw_status,
    dir_pw_string,
  ]
  inputs = [
    # This header is used when FuzzTest is enabled, and not in the GN build.
    # It is listed here to satisfy the source_is_in_gn_build check.
    "private/pw_fuzzer/internal/fuzztest.h",
  ]
}

pw_test("fuzztest_tests") {
  sources = [ "domain_test.cc" ]
  deps = [ ":fuzztest.disabled" ]
}

################################################################################
# libFuzzer support
#
# Create libFuzzer-style fuzzers by using the `pw_fuzzer` template from
# fuzzer.gni.

# Add flags for linking against compiler-rt's libFuzzer. This is added
# automatically by `pw_fuzzer`.
config("libfuzzer_config") {
  ldflags = [ "-fsanitize=fuzzer" ]
}

# Add flags for adding LLVM sanitizer coverage for fuzzing. This is added by
# the host_clang_fuzz toolchains.
config("instrumentation") {
  cflags = [ "-fsanitize=fuzzer-no-link" ]
}

# Includes wrapper's for LLVM's libFuzzer compiler runtime library.
pw_source_set("libfuzzer") {
  public = [
    "public/pw_fuzzer/asan_interface.h",
    "public/pw_fuzzer/fuzzed_data_provider.h",
  ]
  public_configs = [ ":public_include_path" ]
  public_deps = [ dir_pw_log ]
}

# This can be linked against fuzz target functions to create unit tests for
# them.
pw_source_set("libfuzzer_test") {
  testonly = pw_unit_test_TESTONLY
  sources = [ "pw_fuzzer_disabled.cc" ]
  public_deps = [ ":libfuzzer" ]
  deps = [ dir_pw_unit_test ]
}

# libFuzzer-based fuzzers have a distinct dep graph.
group("fuzzers") {
  deps = [ "examples/libfuzzer:fuzzers" ]
}
