// Copyright 2026 The Pigweed Authors
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// DOCSTAG: [pw_rpc-examples-chat-proto]
syntax = "proto3";

package chat;

service Chat {
  // Returns information about a chatroom.
  rpc GetRoomInformation(RoomInfoRequest) returns (RoomInfoResponse);

  // Lists all of the users in a chatroom.
  rpc ListUsersInRoom(ListUsersRequest) returns (stream ListUsersResponse);

  // Uploads a file, in chunks, to a chatroom.
  rpc UploadFile(stream UploadFileRequest) returns (UploadFileResponse);

  // Sends messages to a chatroom while receiving messages from other users.
  rpc SendMessage(stream ChatMessage) returns (stream ChatMessage);
}

message RoomInfoRequest {
  string room = 1;
}

message RoomInfoResponse {
  string room = 1;
  uint32 users = 2;
}

message ListUsersRequest {
  string room = 1;
}

message ListUsersResponse {
  string user = 1;
}

message UploadFileRequest {
  bytes chunk = 1;
}

message UploadFileResponse {
  uint32 bytes_received = 1;
}

message ChatMessage {
  string msg = 1;
  uint32 timestamp = 2;
}
// DOCSTAG: [pw_rpc-examples-chat-proto]
